vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /imgs/avatars
            upload_destination: '%kernel.project_dir%/assets/imgs/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
